name = "nostalgic"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "nostalgic-db"
database_id = "5a4d7f7b-7466-476f-aa52-a8997477724a"
